### ISSUE TITLE
How do I modify the code base

### ISSUE THREAD

**Issue by jianandeng023** [sicara/easy-few-shot-learning#107]
Recently, I was studying the classification of small sample learning, hoping to design my own network through your code base, but I found that after I modified the source code after installing EasyFSL, there was no change in the running time. I hope you can answer my questions. I wish you all the best

**Comment by ebennequin** [comment]
Hi! 

- What modifications did you make to the code?
- What command did you run?
- What was the result you expected?
- What was the actual result?

Please be as specific as you can and share your code and stack trace so I can understand your problem.
