### ISSUE TITLE
SimpleShot implementation doesn't do centering?

### ISSUE THREAD

**Issue by alanqrwang** [sicara/easy-few-shot-learning#108]
The current implementation of SimpleShot doesn't seem to perform the centering feature transformation, as described in the [paper](https://arxiv.org/pdf/1911.04623.pdf). Currently, it seems the implementation only performs L2 normalization and Euclidean distance (i.e. cosine distance). Are there plans to add the centering transformation?

**Comment by ebennequin** [comment]
Adding optional center-normalization of features to all methods is on the roadmap. If you need it fast, your contribution is welcome!
