### ISSUE TITLE
How to use MatchingNetworks or RelationNetworks?

### ISSUE THREAD

**Issue by ShraaboniSarker** [sicara/easy-few-shot-learning#111]
How to use MatchingNetworks for classical training? I replaced the PrototypicalNetwork with MatchingNetwork in the training but i am getting this error "__init__() missing 1 required keyword-only argument: feature_dimension'". But it should get the dimension value from FewShotClassifier. I might be wrong. Please give me some guidance. Same for RelationNetwork.

**Comment by ebennequin** [comment]
Hi! Matching Networks and Relation Networks need an extra argument `feature_dimension` because they use an additional module on top of the feature space. In `__init__()`, we initialize this module, therefore we need the feature dimension.

**Comment by ShraaboniSarker** [comment]
I got it later on. Solved it 2 days ago but forgot to update in the ticket. Thanks.
Btw I am trying to implement the SimpleShot and is there any sample code snippet for that which will help me with the implementation?

**Comment by ebennequin** [comment]
SimpleShot is included in easyfsl ([source](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/methods/simple_shot.py)).
