### ISSUE TITLE
CUDA out of memory when using matching networks

### ISSUE THREAD

**Issue by tommasoguidi** [sicara/easy-few-shot-learning#116]
**ROOT ISSUE**
I adapted your colab notebook for episodic training to use it along with matching networks but it keeps going out of memory. The fact is that I'm using a light resnet18, and a very low number of examples (5-way 1-shot with 4 queries per class). Images themselves are low resolution 256x256 pixel. On the other hand I'm training on a NVIDIA RTX A4000 with 16Gb of dedicated memory (in the log that I will attach to this thread the actual memory available was limited by another process running in the background, but in the meanwhile I killed it and now it's all free).

What I want to understand is how could such a good GPU run out of memory with such a lightweight experiment. I'm not used to episodic training and I just started to use your package, I'm more used to a batch-mode training, but if I'm right an episode should be like a batch, so I don't understand how 5*(1+4)=25 small images + a resnet18 + a LSTM can full such a gpu. Maybe I'm missing something and I'm sure you can help me fix this issue, anyway I'm pasting the error log starting from the last line related to my custom code:

```
File "/home/deepmammo/tommaso/prove/nn_project/fsl.py", line 186, in train_one_epoch
    model.process_support_set(support_images, support_labels)   # usa il support set per fine tuning
File "/home/deepmammo/anaconda3/envs/deepmammo/lib/python3.9/site-packages/easyfsl/methods/matching_networks.py", line 89, in process_support_set
    self.contextualized_support_features = self.encode_support_features(
File "/home/deepmammo/anaconda3/envs/deepmammo/lib/python3.9/site-packages/easyfsl/methods/matching_networks.py", line 147, in encode_support_features
    hidden_state = self.support_features_encoder(support_features.unsqueeze(0))[
File "/home/deepmammo/anaconda3/envs/deepmammo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
File "/home/deepmammo/anaconda3/envs/deepmammo/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 774, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 274.00 MiB (GPU 0; 15.73 GiB total capacity;
6.39 GiB already allocated; 229.00 MiB free; 6.48 GiB reserved in total by PyTorch)
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**CHILD ISSUE**
Another problem comes when I try to follow the hint about max_split_size. In fact, following the [pytorch guide](https://pytorch.org/docs/stable/notes/cuda.html#memory-management), I set the environment variable as they suggest and also set `backend:native` because they say that otherwise the max_split_size won't work. Doing this results in this problem:

```
RuntimeError: Unrecognized CachingAllocator option: backend
```

Despite this being 99.9% a problem related with my pytorch/cuda installation, I wanted to ask you which version of each package is the most suggested. I'm using pytorch 1.13.0 with cuda version 11.7, while my local cuda version is 12.1 (don't know if this can rise a conflict, I never understood whot really happened behind the cuda curtain).

**QUESTION**

Another question that I wanted to ask is related to the `feature_dimension` parameter of the Matching Network. I understood what it means, but I thought that the dimension of the feature vector for the resent18 was 512, but if I set it to that value I get the error:

```
ValueError: Expected feature dimension is 512, but got 2048.
```

I simply fixed it by setting `feature_dimension=2048` but I was pretty sure that the dimension should have been 512

Thanks for any reply.

**Comment by ebennequin** [comment]
Hi,

I'm sorry I can't know for sure what is causing your out-of-memory issue and can't reproduce it at home.

Same for the feature dimension, I ran the following code and got the expected dimension of 512 for the features.

```python

import torch

from easyfsl.methods import MatchingNetworks
from easyfsl.modules import resnet18


support_set = torch.rand((10, 3, 224, 224))
query_set = torch.rand((5, 3, 224, 224))

backbone = resnet18()

print(backbone(support_set).shape)  # (10, 512)


classifier = MatchingNetworks(backbone=backbone, feature_dimension=512)

classifier.process_support_set(support_set, torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]))
print(classifier(query_set).shape)  # (5, 2)
```
