### ISSUE TITLE
PicklingError on "my_first_few_shot_classifier" cell 23. 

### ISSUE THREAD

**Issue by ghos1y** [sicara/easy-few-shot-learning#118]
**Describe the bug**
PicklingError on "my_first_few_shot_classifier" cell 23 while running local
I have already set "num_workers=0". 

**To Reproduce**
1. Code

      # Train the model yourself with this cell
      log_update_frequency = 10
      
      all_loss = []
      model.train()
      with tqdm(enumerate(train_loader), total=len(train_loader)) as tqdm_train:
          for episode_index, (
              support_images,
              support_labels,
              query_images,
              query_labels,
              _,
          ) in tqdm_train:
              loss_value = fit(support_images, support_labels, query_images, query_labels)
              all_loss.append(loss_value)
      
              if episode_index % log_update_frequency == 0:
                  tqdm_train.set_postfix(loss=sliding_average(all_loss, log_update_frequency))

2. Stack trace

---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
[c:\my_first_few_shot_classifier.ipynb](file:///C:/my_first_few_shot_classifier.ipynb) Cell 23 line 7
      [5](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=4) all_loss = []
      [6](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=5) model.train()
----> [7](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=6) with tqdm(enumerate(train_loader), total=len(train_loader)) as tqdm_train:
      [8](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=7)     for episode_index, (
      [9](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=8)         support_images,
     [10](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=9)         support_labels,
   (...)
     [13](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=12)         _,
     [14](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=13)     ) in tqdm_train:
     [15](vscode-notebook-cell:/c%3A/my_first_few_shot_classifier.ipynb#X31sZmlsZQ%3D%3D?line=14)         loss_value = fit(support_images, support_labels, query_images, query_labels)

File [~\AppData\Roaming\Python\Python311\site-packages\torch\utils\data\dataloader.py:441](https://file+.vscode-resource.vscode-cdn.net/c%3A//~/AppData/Roaming/Python/Python311/site-packages/torch/utils/data/dataloader.py:441), in DataLoader.__iter__(self)
    439     return self._iterator
    440 else:
--> 441     return self._get_iterator()

File [~\AppData\Roaming\Python\Python311\site-packages\torch\utils\data\dataloader.py:388](https://file+.vscode-resource.vscode-cdn.net/c%3A//~/AppData/Roaming/Python/Python311/site-packages/torch/utils/data/dataloader.py:388), in DataLoader._get_iterator(self)
    386 else:
    387     self.check_worker_number_rationality()
--> 388     return _MultiProcessingDataLoaderIter(self)

File [~\AppData\Roaming\Python\Python311\site-packages\torch\utils\data\dataloader.py:1042](https://file+.vscode-resource.vscode-cdn.net/c%3A//~/AppData/Roaming/Python/Python311/site-packages/torch/utils/data/dataloader.py:1042), in _MultiProcessingDataLoaderIter.__init__(self, loader)
   1035 w.daemon = True
   1036 # NB: Process.start() actually take some time as it needs to
   1037 #     start a process and pass the arguments over via a pipe.
   1038 #     Therefore, we only add a worker to self._workers list after
   1039 #     it started, so that we do not call .join() if program dies
   1040 #     before it starts, and __del__ tries to join but will get:
   1041 #     AssertionError: can only join a started process.
-> 1042 w.start()
   1043 self._index_queues.append(index_queue)
   1044 self._workers.append(w)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\multiprocessing\process.py:121, in BaseProcess.start(self)
    118 assert not _current_process._config.get('daemon'), \
    119        'daemonic processes are not allowed to have children'
    120 _cleanup()
--> 121 self._popen = self._Popen(self)
    122 self._sentinel = self._popen.sentinel
    123 # Avoid a refcycle if the target function holds an indirect
    124 # reference to the process object (see bpo-30775)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\multiprocessing\context.py:224, in Process._Popen(process_obj)
    222 @staticmethod
    223 def _Popen(process_obj):
--> 224     return _default_context.get_context().Process._Popen(process_obj)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\multiprocessing\context.py:336, in SpawnProcess._Popen(process_obj)
    333 @staticmethod
    334 def _Popen(process_obj):
    335     from .popen_spawn_win32 import Popen
--> 336     return Popen(process_obj)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\multiprocessing\popen_spawn_win32.py:94, in Popen.__init__(self, process_obj)
     92 try:
     93     reduction.dump(prep_data, to_child)
---> 94     reduction.dump(process_obj, to_child)
     95 finally:
     96     set_spawning_popen(None)

File [c:\Program](file:///C:/Program) Files\Python311\Lib\multiprocessing\reduction.py:60, in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)

PicklingError: Can't pickle <function <lambda> at 0x0000015C241818A0>: attribute lookup <lambda> on __main__ failed

**Comment by ebennequin** [comment]
Hi, it seems that your DataLoader is still using multiprocessing. The switch (visible in your stack trace) is performed in the `_get_iterator()` method. From the source code for [`torch.utils.data.DataLoader`](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader):

```python
    def _get_iterator(self) -> '_BaseDataLoaderIter':
        if self.num_workers == 0:
            return _SingleProcessDataLoaderIter(self)
        else:
            self.check_worker_number_rationality()
            return _MultiProcessingDataLoaderIter(self)
```

Your stack trace indicates that you are in the `else` case. Can you check `train_loader.num_workers == 0` right before the start of the loop?

Please also specify your `torch` version.

**Comment by ghos1y** [comment]
thank you for the response but I just used wsl to run the code everything worked fine. I assume it's a problem specific toh windows
