### ISSUE TITLE
Plant Village Dataset for FSL

### ISSUE THREAD

**Issue by ghos1y** [sicara/easy-few-shot-learning#119]
**Problem**
I would like to use the plant village dataset for leaf disease detection using prototypical network. But I don't know how to convert it for easy fsl.

**How can we help**
How should I interpret or handle the dataset so it will work with easy-fsl

**Comment by ebennequin** [comment]
Hi, EasyFSL contains several tools to help you use your own datasets (from the repo's ReadMe):

- [FewShotDataset](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/few_shot_dataset.py): an abstract class to standardize the interface of any dataset you'd like to use
- [EasySet](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/easy_set.py): a ready-to-use FewShotDataset object to handle datasets of images with a class-wise directory split
- [WrapFewShotDataset](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/wrap_few_shot_dataset.py): a wrapper to transform any dataset into a FewShotDataset object
- [FeaturesDataset](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/features_dataset.py): a dataset to handle pre-extracted features
- [SupportSetFolder](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/support_set_folder.py): a dataset to handle support sets stored in a directory

Depending on your specific use case you may want to use any of these tools.
