### ISSUE TITLE
Different image size.

### ISSUE THREAD

**Issue by vsantjr** [sicara/easy-few-shot-learning#123]
**Problem**
I want to run the Colab classical_training notebook with my own dataset.

**Considered solutions**
Currently, I want to understand the splits and sizes of datasets (train, val, test) of the CUB dataset.

**How can we help**
I understand that cub.py import EasySet. But class  EasySet uses ```image_size: int = 84```. I need to redefine this to 256 or even having the possibility to vary this size. How can I easily do it if I am running in Colab?

Thanks.

**Comment by ebennequin** [comment]
Since `CUB` extends `EasySet`, you can initialize with with any argument of `EasySet`, _e.g._ `CUB(split=train, image_size=256)` should work fine.

**Comment by vsantjr** [comment]
Thank you @ebennequin. It worked.
