### ISSUE TITLE
Name of the images (files) of the support and query images.

### ISSUE THREAD

**Issue by vsantjr** [sicara/easy-few-shot-learning#127]
**Problem**
For each test task, I would like to know precisely which are the name of the images (files) which are part of the task. And the respective classes. For instance, assuming 3-way 5-shots and n_query = 10. Hence, we have 15 images in the support set and 10 images in the query set. What are the name of the files and classes/labels of the 15 support images and of the 10 query images?

**Considered solutions**
Not sure. Maybe change the TaskSampler?

**How can we help**
Please provide a solution.

Thank you.

**Comment by ebennequin** [comment]
From the code in [TaskSampler](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/samplers/task_sampler.py), here is how your task is constructed:

```python
    def episodic_collate_fn(
        self, input_data: List[Tuple[Tensor, Union[Tensor, int]]]
    ) -> Tuple[Tensor, Tensor, Tensor, Tensor, List[int]]:
        """
        Collate function to be used as argument for the collate_fn parameter of episodic
            data loaders.
        Args:
            input_data: each element is a tuple containing:
                - an image as a torch Tensor of shape (n_channels, height, width)
                - the label of this image as an int or a 0-dim tensor
        Returns:
            tuple(Tensor, Tensor, Tensor, Tensor, list[int]): respectively:
                - support images of shape (n_way * n_shot, n_channels, height, width),
                - their labels of shape (n_way * n_shot),
                - query images of shape (n_way * n_query, n_channels, height, width)
                - their labels of shape (n_way * n_query),
                - the dataset class ids of the class sampled in the episode
        """
```

As you can see, you already have the ids of the dataset as the last element of the yielded tuple. But if you also want the image path, you need to:

1. Add it to the outputs of your dataset's `__get_item__()` method;
2. Build a new sampler extending the `TaskSampler` class and overwriting the `episodic_collate_fn()` method to handle this additional element. The method's signature would look something like that:

```python
    def episodic_collate_fn(
        self, input_data: List[Tuple[Tensor, Union[Tensor, int], Path]]
    ) -> Tuple[Tensor, Tensor, Tensor, Tensor, List[int], List[Path], List[Path]]:
        """
        Collate function to be used as argument for the collate_fn parameter of episodic
            data loaders.
        Args:
            input_data: each element is a tuple containing:
                - an image as a torch Tensor of shape (n_channels, height, width)
                - the label of this image as an int or a 0-dim tensor
                - the path to this image
        Returns:
            tuple(Tensor, Tensor, Tensor, Tensor, list[int]): respectively:
                - support images of shape (n_way * n_shot, n_channels, height, width),
                - their labels of shape (n_way * n_shot),
                - query images of shape (n_way * n_query, n_channels, height, width)
                - their labels of shape (n_way * n_query),
                - the dataset class ids of the class sampled in the episode,
                - paths of support images of length (n_way * n_shot),
                - paths of query images of length (n_way * n_query),
        """
```

**Comment by vsantjr** [comment]
Thank you @ebennequin. I will try. Regarding this point: "Add it to the outputs of your dataset's ```__get_item__()``` method;" In fact, I should change the ```__get_item__()``` method in the EasySet class. Just to be sure.

**Comment by ebennequin** [comment]
I wouldn't recommend modifying the `easyfsl` code or interface. The best practice would be to create a new class extending `FewShotDataset` with your desired interface.
