### ISSUE TITLE
How to use Prototypical Networks in production?

### ISSUE THREAD

**Issue by durach** [sicara/easy-few-shot-learning#128]
I learned and played with [my_first_few_shot_classifier](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb). Read some source code of the module. Great library, thanks a lot! 

**Problem**

I should have spent more time researching the topic, but I would appreciate advice on the typical way of making predictions in the FSL world, especially with Prototypical Networks. 

In my task, I have ~1000 classes in the support set and ~100 images (one at a time) in my query set. As usual, I need to predict a class name for each image from the query set.

**My assumption**
1. Create prototypes of all images (mean of all embeddings per class)
2. Calc Euclidean distance between the query image and each prototype
3. Take the max score (min distance)

**How can we help**
1. Is there something more efficient than what I described above?
2. Let me know if there is something already implemented in the module, please;

**Comment by ebennequin** [comment]
Hi! Is there any reason why `easyfsl.methods.PrototypicalNetworks` would not be appropriate in your case?

Note that if you have a lot of classes, it may become suboptimal to compare each query image to each class prototype, and [vector databases](https://www.sicara.fr/blog-technique/how-to-choose-your-vector-database-in-2023) could help you gain in efficiency. However I recommend that you get things working without it at first.

**Comment by durach** [comment]
Thank you for getting back to me so quickly. 

In general, am I right in my assumption that I need to run the model with these query images against a batch of support images?

Thank you. I'll check out `easyfsl.methods.PrototypicalNetworks`, as I see it is the more high-level implementation of the code in the notebook I looked at.

As for vector DB, probably you're right, but I need to have my prototype working at least)

**Comment by ebennequin** [comment]
I suggest you check [this notebook](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/inference_with_extracted_embeddings.ipynb) which has the most efficient and recommended method for performing inference with prototypical classification.

**Comment by durach** [comment]
Thank you!
