### ISSUE TITLE
Is there any timeline on MAML?

### ISSUE THREAD

**Issue by jmandivarapu1** [sicara/easy-few-shot-learning#13]
HI,

I really loved your repo and implementation. Just want to check if there any timeline on when the MAML based code will be out?

**Comment by ebennequin** [comment]
Hi,

Thanks for your kind words! At this time I don't have a timeline for MAML. I don't have a technical strategy prepared yet but I feel it's a bit more complicated than the others because of the duality inner-loop / outer-loop and because the architecture of the model depends on the number of classes (while already implemented methods can seemlessly handle tasks with different numbers of classes).

But if you want to contribute by implementing MAML, I'd be thrilled to help you!

**Comment by pranay-ar** [comment]
Hi @ebennequin, I found this really helpful. Is there one for Few Shot Object Detection too?

**Comment by ebennequin** [comment]
Thanks @pranay-ar! I am not working of few-shot detection at the time. If you're looking for something equivalent in few-shot detection, I advise you look at [this repo](https://github.com/ucbdrive/few-shot-object-detection) :smiley:

**Comment by jmandivarapu1** [comment]
> Thanks @pranay-ar! I am not working of few-shot detection at the time. If you're looking for something equivalent in few-shot detection, I advise you look at [this repo](https://github.com/ucbdrive/few-shot-object-detection) 😃



> Hi,
> 
> Thanks for your kind words! At this time I don't have a timeline for MAML. I don't have a technical strategy prepared yet but I feel it's a bit more complicated than the others because of the duality inner-loop / outer-loop and because the architecture of the model depends on the number of classes (while already implemented methods can seemlessly handle tasks with different numbers of classes).
> 
> But if you want to contribute by implementing MAML, I'd be thrilled to help you!

Sure I can help if any time adjusts in the fall. But I am using the way you build the dataloader. It is pretty fast when compared to lear2learn and other packages for custom datasets. 

It would great if you can add demo code for relational networks, matching networks also. As that is no as simple import as prototypical networks.

**Comment by ebennequin** [comment]
That would be great, please reach out to me whenever you can and want to do this!

`It would great if you can add demo code for relational networks, matching networks also. As that is no as simple import as prototypical networks.`
Good idea, I'll do that soon.
