### ISSUE TITLE
Cannot run the tutorial notebook in the local pc

### ISSUE THREAD

**Issue by DickHanselRyan** [sicara/easy-few-shot-learning#135]
**Problem**
I was trying the first few shot learning classifier by re-writing the whole code onto my PC, and when I got into the part of plotting the images, my VSCode showed an issue with Pickle.

![Screenshot 2024-02-06 225324](https://github.com/sicara/easy-few-shot-learning/assets/83385410/1b776792-783a-4edc-823b-b6327ba58bdc)

**Considered solutions**
I can run it on Google Colab, but I want to try and run it on my local environment. I use Python 3.10.13 with the latest EasyFSL version, torch=2.2 and cuda=12.1

**Comment by ebennequin** [comment]
This seems to be the same issue as #51 and it's related to multiprocessing issues with Windows. Follow [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) or disable multiprocessing in the DataLoader by setting `num_workers=0`.

**Comment by DickHanselRyan** [comment]
Hi, I've set the num_workers=0 and it works, but now I am facing another issue as shown on the screenshot.
![image](https://github.com/sicara/easy-few-shot-learning/assets/83385410/a8973ed3-4c5d-417d-aaaa-72197021ebcf)
![image](https://github.com/sicara/easy-few-shot-learning/assets/83385410/58ff034c-5d81-4478-9b20-69baf4fb802e)

**Comment by ebennequin** [comment]
It seems to be the exact same issue but with `train_loader` instead of `test_loader`. Did you set `nuù_workers=0` for both?

**Comment by DickHanselRyan** [comment]
Thanks, I forgot to set the other num_workers=0 and got the same problem. It's fixed now. Thanks for the help.
