### ISSUE TITLE
The link is died.

### ISSUE THREAD

**Issue by DavidZyy** [sicara/easy-few-shot-learning#139]
The [link](https://www.sicara.fr/blog-technique/2019-07-30-image-classification-few-shot-meta-learning-5fd736a6c54d2) in the [First steps into few-shot image classification](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb) is died.

**Comment by ebennequin** [comment]
Thank you for the report! It should be fixed now.
