### ISSUE TITLE
How to train on custom data

### ISSUE THREAD

**Issue by chetanmr** [sicara/easy-few-shot-learning#14]
Hi Thank you for your great work and sharing it with everyone.

I want to implement few shot learning for a task that I have. where I have collected few samples(10) each for both positive and negative class. How do I train the model on these novel classes using my custom dataset.

Thank you for your help

**Comment by ebennequin** [comment]
Hi!

Custom datasets can be used directly with [EasySet](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/data_tools/easy_set.py). You just need to create an `EasySet` instance specifying a JSON spec file following the template defined in the `EasySet` documentation.

I hope this helped. Please tell me if anything is unclear or doesn't work :)

**Comment by chetanmr** [comment]
Hi Thanks for your help.

I have one question - I only have two classes in my dataset, can i reuse the same classes in the train.json, val.json, and test.json. I am asking this since i see that CUB dataset uses different classes in all three files.

Thank you

**Comment by ebennequin** [comment]
Academic benchmarks use distinct sets of classes for training, validation and test, because we want to evaluate a model's ability to generalize to new classes. But you can use the same classes, this won't raise any error.
