### ISSUE TITLE
Failed to download CUB dataset in Google Colab on example Notebooks

### ISSUE THREAD

**Issue by rinevard** [sicara/easy-few-shot-learning#161]
**Describe the bug**
The CUB dataset download command fails when running in Google Colab environment.

**To Reproduce**
1. Open the project notebook, 'episodic_training.ipynb' for example, in Google Colab
2. Run the cell containing `!make download-cub`
3. The download fails, getting a 2.4KB HTML file instead of the actual dataset

**Comment by ebennequin** [comment]
Google Drive tends to block wget downloads. You can manually download the archive from [this link](https://docs.google.com/uc?export=download&id=1GDr1OkoXdhaXWGA8S3MAq3a522Tak-nx).

I have added a comment to the Makefile to share this instruction.

**Comment by arjungupta1012** [comment]
> Google Drive tends to block wget downloads. You can manually download the archive from [this link](https://docs.google.com/uc?export=download&id=1GDr1OkoXdhaXWGA8S3MAq3a522Tak-nx).
> 
> I have added a comment to the Makefile to share this instruction.


I am trying to download it 
But it shows not found (error 404) 
It seems to be deleted
