### ISSUE TITLE
Papers on this project

### ISSUE THREAD

**Issue by tanbin5070** [sicara/easy-few-shot-learning#19]
Hello, author.
Can you tell me the corresponding paper of this source code?
thank you

**Comment by ebennequin** [comment]
Hi! This code is not linked to a particular paper, it's just meant to make your experiments easier. 

You can still cite it using this bibtex:

```
@software{Bennequin_easyfsl,
author = {Bennequin, Etienne},
license = {MIT},
title = {{easyfsl}},
url = {https://github.com/sicara/easy-few-shot-learning}
}
```

**Comment by tanbin5070** [comment]
okay.
thank you very much

**Comment by tanbin5070** [comment]
> Hi! This code is not linked to a particular paper, it's just meant to make your experiments easier.
> 
> You can still cite it using this bibtex:
> 
> ```
> @software{Bennequin_easyfsl,
> author = {Bennequin, Etienne},
> license = {MIT},
> title = {{easyfsl}},
> url = {https://github.com/sicara/easy-few-shot-learning}
> }
> ```

ok!
Thank you
