### ISSUE TITLE
Precomputing support vectors once

### ISSUE THREAD

**Issue by ismael-elatifi** [sicara/easy-few-shot-learning#3]
I have a suggestion of improvement for your model API. I would take the support images as parameter only in the constructor and not in forward() and precompute their feature vectors once for all at model creation time.
And then in your forward method you take only query images as input.
It allows to make multiple forward calls without recomputing support feature vectors each time.
It is also more intuitive because forward usually takes as input only elements for which we want a prediction (query images here).
You can optionally add methods to update the support images (to add or remove some for example).

**Comment by ebennequin** [comment]
Hi! Thanks a lot for your feedback. I've implemented your suggestion, there is now a `process_support_set `method to be called ahead of the `forward` method.

```python
model = PrototypicalNetworks(convolutional_network)
model.process_support_set(support_images, support_labels)
predicted_query_labels = model(query_images)
```

It will be integrated in the next PyPi release.
