### ISSUE TITLE
How to make top5 accuracy?

### ISSUE THREAD

**Issue by mgradyn** [sicara/easy-few-shot-learning#33]

**Comment by ebennequin** [comment]
Hi!

You can see that the [built-in evaluation methods](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/methods/utils.py) only record the number of correct predictions (top-1-wise), so they can't be used for other metrics such as top-k accuracy.

For this, I have this snippet of code from another project:

```python
def top_k_accuracies(results: pd.DataFrame, k: List[int]) -> pd.DataFrame:
    results = results.sort_values(
        ["task_id", "image_id", "score"], ascending=[True, True, False]
    ).assign(is_ok=lambda df: df.true_label == df.predicted_label)

    return pd.DataFrame(
        {
            f"top_{k_instance}": (
                results.groupby(["task_id", "image_id"])
                .head(k_instance)
                .groupby(["task_id", "image_id"])
                .is_ok.any()
                .reset_index()
                .groupby("task_id")
                .is_ok.mean()
            )
            for k_instance in k
        }
    )
```

It can be applied to a DataFrame recording, for each query image of each task, its predicted score for each possible class. Here you have an example for 3-way classification.

| task_id | image_id | true_label | predicted_label | score |
|---------|:--------:|:----------:|:---------------:|:-----:|
| 0       | 0        | 1          | 0               | 0.7   |
| 0       | 0        | 1          | 1               | 0.2   |
| 0       | 0        | 1          | 2               | 0.1   |

If you apply `top_k_accuracies(results=the_above_table, k=[1,2])` it should output a DataFrame looking like this:

task_id | top_1 | top_2
-- | -- | --
0 | 0.0 | 1.0

Hope it helps! If others request it, I might add this to EasyFSL's utilities :)

**Comment by mgradyn** [comment]
Hi, thanks for your answer. Hopefully this will be added to the EasyFSL's utilities
