### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by mgmalana** [sicara/easy-few-shot-learning#37]
**Describe the bug**
This is very small typo but in README.md, if you click on example of classical training, it goes to episodic notebook. 

**To Reproduce**
1. Click "Example of classical training"

Not sure if I should add pull request or raise an issue when I find small typos. Let me know :)

**Comment by ebennequin** [comment]
Thank you so much for the feedback, I fixed it :smile: 

If you know how to fix a problem the easiest thing for me is if you add a pull request, but if you don't have time to do so raising an issue is perfectly fine as well. Either way, it's a huge help!
