### ISSUE TITLE
Finetune: "does not require grad and does not have a grad_fn"

### ISSUE THREAD

**Issue by Jackieam** [sicara/easy-few-shot-learning#40]
**Problem**
I am trying to train backbone using classical training, and use Finetune in methods to fine-tune the model by episodic_training.ipynb. How should I implement it? I see that the episodic_training.ipynb you wrote has fixed the parameters for backbone, but when I import the pre-trained model for fintune, it does not work properly. 
Another question is, how much is n_validation_tasks generally set to? Is there a standard? Because the setting of this hyperparameter will affect the result. I look forward to your answer.

convolutional_network = resnet50(num_classes=2).to(DEVICE)
convolutional_network.load_state_dict(torch.load('save_model/resnet50.pt'))
few_shot_classifier = Finetune(convolutional_network).to(DEVICE)

**Comment by ebennequin** [comment]
Hi! Could you please share some more details on your issue with `Finetune`? What error or unexpected behaviour are you getting?

Regarding the number of validation tasks, there is no standard I am aware of. If you're using the validation set (as in this notebook) to monitor your training you want to keep the number of tasks relatively small so that it does not take more time than the actual training. If you're using the validation set to tune your method's hyperparameters, you may use more tasks.

**Comment by Jackieam** [comment]
Thank you for your reply!
I try to use  episodic_training.ipynb for finetune in my own dataset, where the weight of backbone was training on classical training, and the format of the dataset for training (such as json file) is same as CUB in the tutorial.  I tried to load the  weight for ResNet model. But in training process, an error is reported that there is no gradient. Maybe I need to freeze backbone and set_grad_enabled is True for classifier? The details showed below:
`# Ensure working directory is the project's root
%cd ..

from pathlib import Path
import random
from statistics import mean

import numpy as np
import torch
from torch import nn
from tqdm import tqdm

random_seed = 0
np.random.seed(random_seed)
torch.manual_seed(random_seed)
random.seed(random_seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

n_way = 2
n_shot = 3
n_query = 2

DEVICE = "cuda:0"
n_workers = 4

from easyfsl.datasets import pf_ILD
from easyfsl.samplers import TaskSampler
from torch.utils.data import DataLoader


n_tasks_per_epoch = 500
n_validation_tasks = 500

# Instantiate the datasets
train_set = pf_ILD(split="train", training=True)
val_set = pf_ILD(split="val", training=False)

# Those are special batch samplers that sample few-shot classification tasks with a pre-defined shape
train_sampler = TaskSampler(
    train_set, n_way=n_way, n_shot=n_shot, n_query=n_query, n_tasks=n_tasks_per_epoch
)
val_sampler = TaskSampler(
    val_set, n_way=n_way, n_shot=n_shot, n_query=n_query, n_tasks=n_validation_tasks
)

# Finally, the DataLoader. We customize the collate_fn so that batches are delivered
# in the shape: (support_images, support_labels, query_images, query_labels, class_ids)
train_loader = DataLoader(
    train_set,
    batch_sampler=train_sampler,
    num_workers=n_workers,
    pin_memory=True,
    collate_fn=train_sampler.episodic_collate_fn,
)
val_loader = DataLoader(
    val_set,
    batch_sampler=val_sampler,
    num_workers=n_workers,
    pin_memory=True,
    collate_fn=val_sampler.episodic_collate_fn,
)

from easyfsl.methods import PrototypicalNetworks, FewShotClassifier, relation_networks, Finetune
from easyfsl.modules import resnet50, resnet101


convolutional_network = resnet50(num_classes=2).to(DEVICE)
convolutional_network.load_state_dict(torch.load('save_model/resnet50_3_2_50.pt'))
# convolutional_network = resnet50()
# for param in convolutional_network.parameters():
#     param.requires_grad = False
few_shot_classifier = Finetune(convolutional_network).to(DEVICE)

from torch.optim import SGD, Optimizer, Adam
from torch.optim.lr_scheduler import MultiStepLR
from torch.utils.tensorboard import SummaryWriter


LOSS_FUNCTION = nn.CrossEntropyLoss()

n_epochs = 200
scheduler_milestones = [120, 160]
scheduler_gamma = 0.1
learning_rate = 1e-4
tb_logs_dir = Path(".")

train_optimizer = Adam(
    few_shot_classifier.parameters(), lr=learning_rate, weight_decay=5e-4
)
train_scheduler = MultiStepLR(
    train_optimizer,
    milestones=scheduler_milestones,
    gamma=scheduler_gamma,
)

tb_writer = SummaryWriter(log_dir=str(tb_logs_dir))

def training_epoch(
    model: FewShotClassifier, data_loader: DataLoader, optimizer: Optimizer
):
    all_loss = []
    model.train()
    with tqdm(
        enumerate(data_loader), total=len(data_loader), desc="Training"
    ) as tqdm_train:
        for episode_index, (
            support_images,
            support_labels,
            query_images,
            query_labels,
            _,
        ) in tqdm_train:
            optimizer.zero_grad()
            model.process_support_set(
                support_images.to(DEVICE), support_labels.to(DEVICE)
            )
            classification_scores = model(query_images.to(DEVICE))

            loss = LOSS_FUNCTION(classification_scores, query_labels.to(DEVICE))
            loss.backward()
            optimizer.step()

            all_loss.append(loss.item())

            tqdm_train.set_postfix(loss=mean(all_loss))

    return mean(all_loss)

from easyfsl.methods.utils import evaluate


best_state = few_shot_classifier
best_validation_accuracy = 0.0
for epoch in range(n_epochs):
    print(f"Epoch {epoch}")
    average_loss = training_epoch(few_shot_classifier, train_loader, train_optimizer)
    validation_accuracy = evaluate(
        few_shot_classifier, val_loader, device=DEVICE, tqdm_prefix="Validation"
    )

    if validation_accuracy > best_validation_accuracy:
        best_validation_accuracy = validation_accuracy
        best_state = few_shot_classifier.state_dict()
        print("Ding ding ding! We found a new best model!")

    tb_writer.add_scalar("Train/loss", average_loss, epoch)
    tb_writer.add_scalar("Val/acc", validation_accuracy, epoch)

    # Warn the scheduler that we did an epoch
    # so it knows when to decrease the learning rate
    train_scheduler.step()
# Then the error was reported as "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn"
`
I look forward to your reply！

**Comment by ebennequin** [comment]
Thank you, this is way more clear :smile: 

You're trying to use episodic training with the Finetune method, which is an inference-only method, [as stated in the docstring](https://github.com/sicara/easy-few-shot-learning/blob/a770d9a318b72e19d2e81ba86c63f539a2f2ddcc/easyfsl/methods/finetune.py#L16). Since the method involves the freezing of the backbone to optimize the prototypes, it is incompatible with episodic training.

This is also the case for TIM and TransductiveFinetuning.

I suppose you can implement a workaround to use episodic training with those methods, but I don't encourage it, since they are designed for inference only. Instead, I suggest you train your backbone on the train set using classical training.

**Comment by ebennequin** [comment]
Linked to #55
