### ISSUE TITLE
Traning with custom dataset

### ISSUE THREAD

**Issue by gushengzhao1996** [sicara/easy-few-shot-learning#45]
Hi, thanks for your code, it helps me a lot.
But it also got some problems for a newbie like me.
Although I make the code run successfully now,  I also make a lot of compromises to some errors.
I combined the code from [classical_training.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/classical_training.ipynb) and [my_first_few_shot_classifier.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb).

I post all my code step by step and point out the problems I met.
I am running Windows10.
The environment is created by Anaconda.
Cuda10.2, Cudnn 7.0, PyTorch 1.10.1

At last, great thanks for your code again.
Let's discuss this together.

**Comment by gushengzhao1996** [comment]
### **Step 1 Import lib and load datasets** 
`
import torch
from torch import nn, optim
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
from torchvision.models import resnet18
from tqdm import tqdm

from easyfsl.samplers import TaskSampler
from easyfsl.utils import plot_images, sliding_average

from pathlib import Path
import random
from statistics import mean
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import os
import copy

random_seed = 0
np.random.seed(random_seed)
torch.manual_seed(random_seed)
random.seed(random_seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

transform = transforms.Compose([
             transforms.Resize((224, 224)),
             transforms.ToTensor(),
             transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
            ])

data_dir = './competition data/data/'

train_set = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform = transform)
val_set = datasets.ImageFolder(os.path.join(data_dir, 'val'), transform = transform)

train = open("./competition data/train_set.csv","r")
df_train = pd.read_csv(train)
records_train = df_train.to_records(index=False)
list_train = list(records_train)

val = open("./competition data/val_set.csv","r")
df_val = pd.read_csv(val)
records_val = df_val.to_records(index=False)
list_val = list(records_val)

class_names = train_set.classes
`

**Comment by gushengzhao1996** [comment]
### **Step 2 data loader** 

```
batch_size = 64
n_workers = 0

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

train_loader = DataLoader(
    train_set,
    batch_size=batch_size,
    num_workers=n_workers,
    pin_memory=True,
    shuffle=True,
)

n_way = 5
n_shot = 1
n_query = 1
n_validation_tasks = 500

val_set.get_labels = lambda: [
    instance[1] for instance in list_val
]

val_sampler = TaskSampler(
    val_set, n_way=n_way, n_shot=n_shot, n_query=n_query, n_tasks=n_validation_tasks
)

val_loader = DataLoader(
    val_set,
    batch_sampler=val_sampler,
    num_workers=n_workers,
    pin_memory=True,
    collate_fn = val_sampler.episodic_collate_fn,
)
```

**Comment by gushengzhao1996** [comment]
### **Step 4 Optimizer and scheduler**

This part comes from [classical_training.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/classical_training.ipynb).

```
from torch.optim import SGD, Optimizer, Adam
from torch.optim.lr_scheduler import MultiStepLR, ReduceLROnPlateau
from torch.utils.tensorboard import SummaryWriter


LOSS_FUNCTION = nn.CrossEntropyLoss()

n_epochs = 200
scheduler_milestones = [50, 100, 150, 190]
scheduler_gamma = 0.1
learning_rate = 1e-01
tb_logs_dir = Path(".")

train_optimizer = SGD(
    model.parameters(), lr=learning_rate, momentum=0.9, weight_decay=5e-4
)
train_scheduler = MultiStepLR(
    train_optimizer,
    milestones=scheduler_milestones,
    gamma=scheduler_gamma,
)

tb_writer = SummaryWriter(log_dir=str(tb_logs_dir))
```

**Comment by gushengzhao1996** [comment]
### **Step 5 Start training**

This part also comes from [classical_training.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/classical_training.ipynb).
I modified the line of validation part.
Because I use my pre-trained model, it doesn't have` .set_use_fc()`.
I use the concept in transfer learning, call `model.eval()` first so it won't change weights with inputs.
Then call `evaluate()` and `model.train()`.

```
best_state = model.state_dict()
best_model_wts = copy.deepcopy(model.state_dict())
best_validation_accuracy = 0.0
validation_frequency = 4

for epoch in range(n_epochs):
    print(f"Epoch {epoch}")
    average_loss = training_epoch(model, train_loader, train_optimizer)

    if epoch % validation_frequency == validation_frequency - 1:

        # We use this very convenient method from EasyFSL's ResNet to specify
        # that the model shouldn't use its last fully connected layer during validation.
        model.eval()
        validation_accuracy = evaluate(
            few_shot_classifier, val_loader, device = device, tqdm_prefix="Validation"
        )
        model.train()

        if validation_accuracy > best_validation_accuracy:
            best_validation_accuracy = validation_accuracy
            best_state = model.state_dict()
            best_model_wts = copy.deepcopy(model.state_dict())
            print("Ding ding ding! We found a new best model!")

        tb_writer.add_scalar("Val/acc", validation_accuracy, epoch)

    tb_writer.add_scalar("Train/loss", average_loss, epoch)

    # Warn the scheduler that we did an epoch
    # so it knows when to decrease the learning rate
    train_scheduler.step()
```

**Comment by ebennequin** [comment]
Hi @gushengzhao1996, thank you for your kind words and the detailed description of your problem. This is very helpful!

> PicklingError: Can't pickle <function <lambda> at 0x000001B06041C1F8>: attribute lookup <lambda> on __main__ failed

I googled this, and it seems that PyTorch's multiprocessing (used when `num_workers > 0`) has some problems with Windows. I found [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) that might help you to make it work.

> Second is the value setting of n_way, n_shot and n_query.
> I set them to [5, 1, 1] as shown above. However, if set n_shot or n_query bigger even like [5, 2, 1].
> There is an error that occurred in the training process, the error message shows below.
> I think it's because of my datasets. It has 219 classes and each class only has 10 images.

This error occurs when a class's population is strictly smaller than `n_shot + n_query`. I believe the problem is that you have at least one class with only two instances.
The `ImageFolder` dataset that you're using crawls all subfolders of your `root` folder. Can you check the number of files in each subfolder?

**Comment by gushengzhao1996** [comment]
@ebennequin Thanks for your reply.

First problem.
I found someone said add `if __name__ ==  '__main__': ` before your main code would work, like step 2 in [the tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac). But this didn't work.
For the step 1 in [the tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac), I not sure how to do that because it's a very basic function like `for... in ...` loop.
It doesn't affect the training process to much, so I will just leave it there.

Second problem.
Yes, like that's it. I split the dataset myself and set the validation with 0.2, each class in validation has exact 2 images.

**Comment by gushengzhao1996** [comment]
### **another question**
Sorry @ebennequin , I have another question about prediction.
I checked #17  and [my_first_few_shot_classifier.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb), so I have to set the support images and their labels.

1. Support set for prediction.
As I said, my dataset has a total of 219 classes.
What should I do for the support set? Create it from train and validation data?
Use `TaskSampler()` and those parameter to control?

2.How to process the unknown data
I checked the other ones' notebooks in #17.
```
model.eval()
example_scores = model(
    example_support_images.to(device), #.cuda(),
    example_support_labels.to(device),#.cuda(),
    example_query_images.to(device), #.cuda(),
).detach()

_, example_predicted_labels = torch.max(example_scores.data, 1)

print("Ground Truth / Predicted")
for i in range(len(example_query_labels)):
    print(
        f"{valid_set._image_labels[example_class_ids[example_query_labels[i]]]} / {valid_set._image_labels[example_class_ids[example_predicted_labels[i]]]}"
    )
```
I think this part from [my_first_few_shot_classifier.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb) is helpful to me.
Because the dataset(no label) I will use to predict is really big.
But I am not sure how to process the dataset to be like `example_query_images`.
Use `ImageFolder` and `DataLoader` like what I do to the training set above?

**Comment by ebennequin** [comment]
> Second problem. Yes, like that's it. I split the dataset myself and set the validation with 0.2, each class in validation has exact 2 images.

It's common practice in Few-Shot Learning to split the classes (and not the examples inside the classes) between train and val. This way, you're actually validating the ability of your model to solve few-shot tasks on novel classes. In your case, you could save ~40 classes for validation.

As for your additional questions, I have to say I am unsure what problem you're trying to solve or what experiments you're trying to run. Could you give me some context?

**Comment by gushengzhao1996** [comment]
Basically, what I want to do now, is to predict a bunch of images' classes (novel data without labels).
The class is the same as the training set which is a total of 219 classes.

The First is the support set.
Should I create a support set from training data when I am performing prediction?

The second is how to load the novel data for prediction in batch.
As I said, the novel data is huge, so I think it's not a good idea to predict them single by single.
But I am unsure how to load the novel data.
And I googled [this](https://discuss.pytorch.org/t/how-to-load-images-for-inference-in-batch/33329).
Is this the way to load data?
```
data_transforms = {
    'predict': transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    }

dataset = {'predict' : datasets.ImageFolder("./data", data_transforms['predict'])}
dataloader = {'predict': torch.utils.data.DataLoader(dataset['predict'], batch_size = 1, shuffle=False, num_workers=4)}

outputs = list()
since = time.time()
for inputs, labels in dataloader['predict']:
    inputs = inputs.to(device)
    output = model(inputs)
    output = output.to(device)
    index = output.data.numpy().argmax()
    print index
```

**Comment by ebennequin** [comment]
In FSL we usually train the model on a large _base_ dataset, and then apply it on _novel_ classes for which we only have a few examples per class. As I understand it, in your case the 219 classes are the novel classes. With only 10 examples per class, you most likely won't get very good results by training your network on them. Instead, you could use your 219*10 examples (or a subset of them) as your _support set_. Instead of training your own model, you could simply use on-the-shelf models, e.g. from [this great library](https://github.com/rwightman/pytorch-image-models).

As for loading, as I explained in #17, the only requirement of EasyFSL is that the query images are fed in a tensor of shape `(n_images, 3, width, height)`. It seems that the code you provided will work, although

- random preprocessing such as `RandomResizedCrop` or `RandomHorizontalFlip` are usually used for trivial data augmentation during training, but it is odd to use them for inference. You might want to prefer a simple `Resize`
- you probably don't need the dictionary structure with the "predict" key ;
- you may want to increase your batch size when defining the DataLoader.

**Comment by gushengzhao1996** [comment]
Thanks!

**Comment by shraddha291996** [comment]
> ### **Step 2 data loader**
> ```
> batch_size = 64
> n_workers = 0
> 
> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> 
> train_loader = DataLoader(
>     train_set,
>     batch_size=batch_size,
>     num_workers=n_workers,
>     pin_memory=True,
>     shuffle=True,
> )
> 
> n_way = 5
> n_shot = 1
> n_query = 1
> n_validation_tasks = 500
> 
> val_set.get_labels = lambda: [
>     instance[1] for instance in list_val
> ]
> 
> val_sampler = TaskSampler(
>     val_set, n_way=n_way, n_shot=n_shot, n_query=n_query, n_tasks=n_validation_tasks
> )
> 
> val_loader = DataLoader(
>     val_set,
>     batch_sampler=val_sampler,
>     num_workers=n_workers,
>     pin_memory=True,
>     collate_fn = val_sampler.episodic_collate_fn,
> )
> ```
> 
> In step 2, I got 2 problems. First is the `num_workers`. It affects some parts like `for data in val_loader:` or `enumerate(val_loader)`. The error message like below. The solution I used is simple, just make `num_workers = 0`. But I don't think it's the best solution. BTW, this problem also occurs when I was trying [classical_training.ipynb](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/classical_training.ipynb). It may be caused by the enviroment.
> 
> ```
> ---------------------------------------------------------------------------
> PicklingError                             Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_27300\744700885.py in <module>
> ----> 1 for data in val_loader:
>       2     print(data)
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
>     357             return self._iterator
>     358         else:
> --> 359             return self._get_iterator()
>     360 
>     361     @property
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in _get_iterator(self)
>     303         else:
>     304             self.check_worker_number_rationality()
> --> 305             return _MultiProcessingDataLoaderIter(self)
>     306 
>     307     @property
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
>     916             #     before it starts, and __del__ tries to join but will get:
>     917             #     AssertionError: can only join a started process.
> --> 918             w.start()
>     919             self._index_queues.append(index_queue)
>     920             self._workers.append(w)
> 
> ~\Anaconda3\envs\pytorch37\lib\multiprocessing\process.py in start(self)
>     110                'daemonic processes are not allowed to have children'
>     111         _cleanup()
> --> 112         self._popen = self._Popen(self)
>     113         self._sentinel = self._popen.sentinel
>     114         # Avoid a refcycle if the target function holds an indirect
> 
> ~\Anaconda3\envs\pytorch37\lib\multiprocessing\context.py in _Popen(process_obj)
>     221     @staticmethod
>     222     def _Popen(process_obj):
> --> 223         return _default_context.get_context().Process._Popen(process_obj)
>     224 
>     225 class DefaultContext(BaseContext):
> 
> ~\Anaconda3\envs\pytorch37\lib\multiprocessing\context.py in _Popen(process_obj)
>     320         def _Popen(process_obj):
>     321             from .popen_spawn_win32 import Popen
> --> 322             return Popen(process_obj)
>     323 
>     324     class SpawnContext(BaseContext):
> 
> ~\Anaconda3\envs\pytorch37\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
>      87             try:
>      88                 reduction.dump(prep_data, to_child)
> ---> 89                 reduction.dump(process_obj, to_child)
>      90             finally:
>      91                 set_spawning_popen(None)
> 
> ~\Anaconda3\envs\pytorch37\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
>      58 def dump(obj, file, protocol=None):
>      59     '''Replacement for pickle.dump() using ForkingPickler.'''
> ---> 60     ForkingPickler(file, protocol).dump(obj)
>      61 
>      62 #
> 
> PicklingError: Can't pickle <function <lambda> at 0x000001B06041C1F8>: attribute lookup <lambda> on __main__ failed
> ```
> 
> Second is the value setting of `n_way`, `n_shot` and `n_query`. I set them to [5, 1, 1] as shown above. However, if set `n_shot` or `n_query` bigger even like [5, 2, 1]. There is an error that occurred in the training process, the error message shows below. I think it's because of my datasets. It has 219 classes and each class only has 10 images.
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_27300\2390850040.py in <module>
>      14         model.eval()
>      15         validation_accuracy = evaluate(
> ---> 16             few_shot_classifier, val_loader, device = device, tqdm_prefix="Validation"
>      17         )
>      18         model.train()
> 
> ~\AppData\Local\Temp\ipykernel_27300\3882128419.py in evaluate(model, data_loader, device, use_tqdm, tqdm_prefix)
>      57         ) as tqdm_eval:
>      58             #print(tqdm_eval)
> ---> 59             for _, (support_images, support_labels, query_images, query_labels, _,) in tqdm_eval:
>      60                 correct, total = evaluate_on_one_task(
>      61                     model,
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\tqdm\std.py in __iter__(self)
>    1193 
>    1194         try:
> -> 1195             for obj in iterable:
>    1196                 yield obj
>    1197                 # Update and possibly print the progressbar.
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in __next__(self)
>     519             if self._sampler_iter is None:
>     520                 self._reset()
> --> 521             data = self._next_data()
>     522             self._num_yielded += 1
>     523             if self._dataset_kind == _DatasetKind.Iterable and \
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in _next_data(self)
>     558 
>     559     def _next_data(self):
> --> 560         index = self._next_index()  # may raise StopIteration
>     561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>     562         if self._pin_memory:
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py in _next_index(self)
>     510 
>     511     def _next_index(self):
> --> 512         return next(self._sampler_iter)  # may raise StopIteration
>     513 
>     514     def _next_data(self):
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\easyfsl\samplers\task_sampler.py in __iter__(self)
>      59                     )
>      60                     # pylint: enable=not-callable
> ---> 61                     for label in random.sample(self.items_per_label.keys(), self.n_way)
>      62                 ]
>      63             )
> 
> ~\Anaconda3\envs\pytorch37\lib\site-packages\easyfsl\samplers\task_sampler.py in <listcomp>(.0)
>      59                     )
>      60                     # pylint: enable=not-callable
> ---> 61                     for label in random.sample(self.items_per_label.keys(), self.n_way)
>      62                 ]
>      63             )
> 
> ~\Anaconda3\envs\pytorch37\lib\random.py in sample(self, population, k)
>     319         n = len(population)
>     320         if not 0 <= k <= n:
> --> 321             raise ValueError("Sample larger than population or is negative")
>     322         result = [None] * k
>     323         setsize = 21        # size of a small set minus size of an empty list
> 
> ValueError: Sample larger than population or is negative
> ```

Hello,
I am facing the same issue in my training phase , did you find any solution ?

**Comment by shraddha291996** [comment]
> Hi @gushengzhao1996, thank you for your kind words and the detailed description of your problem. This is very helpful!
> 
> > PicklingError: Can't pickle <function  at 0x000001B06041C1F8>: attribute lookup  on **main** failed
> 
> I googled this, and it seems that PyTorch's multiprocessing (used when `num_workers > 0`) has some problems with Windows. I found [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) that might help you to make it work.
> 
> > Second is the value setting of n_way, n_shot and n_query.
> > I set them to [5, 1, 1] as shown above. However, if set n_shot or n_query bigger even like [5, 2, 1].
> > There is an error that occurred in the training process, the error message shows below.
> > I think it's because of my datasets. It has 219 classes and each class only has 10 images.
> 
> This error occurs when a class's population is strictly smaller than `n_shot + n_query`. I believe the problem is that you have at least one class with only two instances. The `ImageFolder` dataset that you're using crawls all subfolders of your `root` folder. Can you check the number of files in each subfolder?

Hi, thank you so much for your amazing work ,  I am facing the same issue in my training phase I have 4 classes in my dataset with the following n way n shot and n query
n_way = 4
n_shot = 1
n_query = 1
Sorry Im new in this and this might be a stupid question but is it necessary to keep same number of samples in train test val set
so all sets have 4 classes just the number of samples in train set each class has 14 images and test val set has 4 images each class. Any suggestions would be helpful. 
Thanks

**Comment by shraddha291996** [comment]
> Hi @gushengzhao1996, thank you for your kind words and the detailed description of your problem. This is very helpful!
> 
> > PicklingError: Can't pickle <function  at 0x000001B06041C1F8>: attribute lookup  on **main** failed
> 
> I googled this, and it seems that PyTorch's multiprocessing (used when `num_workers > 0`) has some problems with Windows. I found [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) that might help you to make it work.
> 
> > Second is the value setting of n_way, n_shot and n_query.
> > I set them to [5, 1, 1] as shown above. However, if set n_shot or n_query bigger even like [5, 2, 1].
> > There is an error that occurred in the training process, the error message shows below.
> > I think it's because of my datasets. It has 219 classes and each class only has 10 images.
> 
> This error occurs when a class's population is strictly smaller than `n_shot + n_query`. I believe the problem is that you have at least one class with only two instances. The `ImageFolder` dataset that you're using crawls all subfolders of your `root` folder. Can you check the number of files in each subfolder?

Hi, thank you so much for your amazing work , I am facing the same issue in my training phase I have 4 classes in my dataset with the following n way n shot and n query
n_way = 4
n_shot = 1
n_query = 1
so I have  4 classes in train test val set just the number of samples in train set each class has 14 images and test val set has 4 images each class. Im following the [gushengzhao1996](https://github.com/gushengzhao1996) steps exactly . Any suggestions would be helpful.
Thanks

**Comment by gushengzhao1996** [comment]
> > Hi @gushengzhao1996, thank you for your kind words and the detailed description of your problem. This is very helpful!
> > > PicklingError: Can't pickle <function  at 0x000001B06041C1F8>: attribute lookup  on **main** failed
> > 
> > 
> > I googled this, and it seems that PyTorch's multiprocessing (used when `num_workers > 0`) has some problems with Windows. I found [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) that might help you to make it work.
> > > Second is the value setting of n_way, n_shot and n_query.
> > > I set them to [5, 1, 1] as shown above. However, if set n_shot or n_query bigger even like [5, 2, 1].
> > > There is an error that occurred in the training process, the error message shows below.
> > > I think it's because of my datasets. It has 219 classes and each class only has 10 images.
> > 
> > 
> > This error occurs when a class's population is strictly smaller than `n_shot + n_query`. I believe the problem is that you have at least one class with only two instances. The `ImageFolder` dataset that you're using crawls all subfolders of your `root` folder. Can you check the number of files in each subfolder?
> 
> Hi, thank you so much for your amazing work , I am facing the same issue in my training phase I have 4 classes in my dataset with the following n way n shot and n query n_way = 4 n_shot = 1 n_query = 1 so I have 4 classes in train test val set just the number of samples in train set each class has 14 images and test val set has 4 images each class. Im following the [gushengzhao1996](https://github.com/gushengzhao1996) steps exactly . Any suggestions would be helpful.
> 

Hi.
I think my problem is a little bit different from yours.
Let me explain something about the [n-way k-shot] setting. As you said, you set n_way = 4 n_shot = 1 n_query = 1, which means each time, it will pick 1 sample from 4 classes that formed the support set, and 1 sample formed the query set.
My problem also occurs in the validation step, because my validation set only has 2 samples in each class. So when I set[5, 2, 1], the Sampler should take 2+1 samples from each class. That's why the Sampler value is larger than the population(the actual sample number in each class of the validation set).
However, as your described, your [n-way k-shot] setting should be ok for your training and validation set.
But since the error occurred in the validation step, first I suggest you check the number of samples in each class of the validation set. 
Second, try to change the [n-way k-shot] setting, set the n-way value smaller(2 or 3).

**Comment by shraddha291996** [comment]
> > > Hi @gushengzhao1996, thank you for your kind words and the detailed description of your problem. This is very helpful!
> > > > PicklingError: Can't pickle <function  at 0x000001B06041C1F8>: attribute lookup  on **main** failed
> > > 
> > > 
> > > I googled this, and it seems that PyTorch's multiprocessing (used when `num_workers > 0`) has some problems with Windows. I found [this tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) that might help you to make it work.
> > > > Second is the value setting of n_way, n_shot and n_query.
> > > > I set them to [5, 1, 1] as shown above. However, if set n_shot or n_query bigger even like [5, 2, 1].
> > > > There is an error that occurred in the training process, the error message shows below.
> > > > I think it's because of my datasets. It has 219 classes and each class only has 10 images.
> > > 
> > > 
> > > This error occurs when a class's population is strictly smaller than `n_shot + n_query`. I believe the problem is that you have at least one class with only two instances. The `ImageFolder` dataset that you're using crawls all subfolders of your `root` folder. Can you check the number of files in each subfolder?
> > 
> > 
> > Hi, thank you so much for your amazing work , I am facing the same issue in my training phase I have 4 classes in my dataset with the following n way n shot and n query n_way = 4 n_shot = 1 n_query = 1 so I have 4 classes in train test val set just the number of samples in train set each class has 14 images and test val set has 4 images each class. Im following the [gushengzhao1996](https://github.com/gushengzhao1996) steps exactly . Any suggestions would be helpful.
> 
> Hi. I think my problem is a little bit different from yours. Let me explain something about the [n-way k-shot] setting. As you said, you set n_way = 4 n_shot = 1 n_query = 1, which means each time, it will pick 1 sample from every 4 classes that formed the support set (total 4 samples), and the same for the query set (also total 4 samples). My problem also occurs in the validation step, because my validation set only has 2 samples in each class. So when I set[5, 2, 1], the Sampler should take 2+1 samples from each class. That's why the Sampler value is larger than the population(the actual sample number in each class of the validation set). However, as your described, your [n-way k-shot] setting should be ok for your training and validation set. But since the error occurred in the validation step, first I suggest you check the number of samples in each class of the validation set. Second, try to change the [n-way k-shot] setting, set the n-way value smaller(2 or 3).

Hi, thank you very much for your reply and suggestions , so basically I tried keeping the different settings for n way k shot  with your suggested values also (2 or 3) but it still gives me the same error. Sorry Im new in this , but I did not exactly get what do you mean by checking the number samples in each class in validation set? Im bit confused in between splitting the classes and number of samples in each classes in train test val  set.  Currently in my val set there are 4 classes and each class has 4 samples and train set 4 classes each has 14 samples. Can you please show your dataset structure ? That would be really helpful.

Thanks

**Comment by gushengzhao1996** [comment]
> 

'checking the number of samples in each class in the validation set' means:
How many classes are in the validation set?
how many samples are in each class above?

My dataset has a total of 219 classes, each class has 10 images (samples).
The ratio of training, testing, and validation is [6,2,2]. all sets have 219 classes.

As I showed, we don't split the class for each set.
BTW, I'm confused by your description.
Usually, we just mention the total number of the whole dataset. Like 'My dataset has N classes, 80% (samples not classes) for the training set, 20% for the validation (testing) set.'
So from your description, it might be a dataset with 4 classes, 8 classes, or between them (4~8).

**Comment by ebennequin** [comment]
> My dataset has a total of 219 classes, each class has 10 images (samples).
> The ratio of training, testing, and validation is [6,2,2]. all sets have 219 classes.

While this may be relevant to your use case, this is not the usual Few-Shot Learning setting, in which the model infers at test time on classes that were not seen during training (nor validation). I assume @shraddha291996 is referring to the usual Few-Shot Learning setting, and therefore their train, val and test classes are different.
