### ISSUE TITLE
Why cannot i use torchvision.models.mobilenet when using "my first few shot classifier"?

### ISSUE THREAD

**Issue by SuSuYMH** [sicara/easy-few-shot-learning#47]
**Problem**
What do you want to do? What is blocking you?

**Considered solutions**
What have you tried but didn't work?

**How can we help**
Be as clear and concise as possible so we can help you in the most efficient way.

**Comment by ebennequin** [comment]
Hi! Can you share your code and stack trace to help me understand your issue?
