### ISSUE TITLE
PicklingError: Can't pickle <function <lambda> at 0x000001AEE1AC88B0>: attribute lookup <lambda> on __main__ failed

### ISSUE THREAD

**Issue by Meoooww** [sicara/easy-few-shot-learning#51]
**Problem**
(i am greenhand in this field, so i may ask a simple and silly question. Sorry for that)
when i run the front part of "my_first_few_shot_classifier.ipynb":
![image](https://user-images.githubusercontent.com/56733007/177071512-050ee733-41fe-44e4-9e40-e7acdab15a45.png)
The following error messages appear：
![image](https://user-images.githubusercontent.com/56733007/177071755-681ad628-90ea-43bf-94cc-4f51546ce367.png)

**How can we help**
How to solve this problem? I haven't found a practical solution

**Comment by kylewangt** [comment]
> **Problem** (i am greenhand in this field, so i may ask a simple and silly question. Sorry for that) when i run the front part of "my_first_few_shot_classifier.ipynb": ![image](https://user-images.githubusercontent.com/56733007/177071512-050ee733-41fe-44e4-9e40-e7acdab15a45.png) The following error messages appear： ![image](https://user-images.githubusercontent.com/56733007/177071755-681ad628-90ea-43bf-94cc-4f51546ce367.png)
> 
> **How can we help** How to solve this problem? I haven't found a practical solution

set num_workers=0

**Comment by ebennequin** [comment]
Hi! As we found while discussing issue #45, it seems that PyTorch's DataLoader's multiprocessing has issues with Windows. 

[This tutorial](https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac) offers a solution to make it work. If it doesn't work for you, as @kylewangt said, you can disable multiprocessing alltogether with `num_workers=0`.
