### ISSUE TITLE
FSL object detection

### ISSUE THREAD

**Issue by shrinand1996** [sicara/easy-few-shot-learning#58]
It will be great if there was a tutorial for Few shot object detection as well.

**Comment by ebennequin** [comment]
Hi! Thanks for the suggestion. I'm not an expert in few-shot object detection so I would not dare to propose a tutorial, but if anyone feels like adding one to the repo I'd be glad to help in any way I can!

**Comment by ynusinovich** [comment]
@shrinand1996 this might be a good one to try: https://github.com/ucbdrive/few-shot-object-detection
