### ISSUE TITLE
How to Use My First Few Shot Classifier with a Custom Dataset

### ISSUE THREAD

**Issue by ynusinovich** [sicara/easy-few-shot-learning#59]
**Problem**
When combining the ["My First Few Shot Classifier"](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb) with a custom dataset from the ["Easy Set"](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/easy_set.py), I got this error: 
```
Exception has occurred: PicklingError
Can't pickle <function <lambda> at 0x13d8f6e50>: attribute lookup <lambda> on __main__ failed
  File "/Users/yannusinovich/Documents/ONX_AI/machine-learning/recommender/issue_logs/few_shot_learning_easyfsl.py", line 279, in <module>
    ) = next(iter(test_loader))
```

**Considered solutions**
1. I created a sample dataset with 4 classes and 4 images per class, and I placed them in folders, as described in "Easy Set", along with a "config.json" defining the classes and where to find them.
2. I changed the references to `test_set` in "My First Few Shot Classifier" to `dataset` since `test_set` wasn't defined.
3. When I ran the code, I got the error `'EasySet' object has no attribute '_flat_character_images'`.
4. I defined `self._flat_images_and_labels: List[Tuple[str, int]] = list(zip(self.images, self.labels))` in the `__init__` of the `EasySet` class, and I changed the sampler code to:
```
N_WAY = 4  # Number of classes in a task
N_SHOT = 4  # Number of images per class in the support set
N_QUERY = 2  # Number of images per class in the query set
N_EVALUATION_TASKS = 10

dataset.get_labels = lambda: [
    instance[1] for instance in dataset._flat_images_and_labels
]
```
The value of `self._flat_images_and_labels` for EasySet looks exaclty the same as Omniglot's `_flat_character_images`, but it runs into the error above at this step:
```
(
    example_support_images,
    example_support_labels,
    example_query_images,
    example_query_labels,
    example_class_ids,
) = next(iter(test_loader))
```

**How can we help**
Could you please provide me some guidance on how to use the ["My First Few Shot Classifier"](https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb) notebook with a custom dataset from the ["Easy Set"](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/easy_set.py)?

**Comment by ebennequin** [comment]
Hi! This seems to be the same error as in #45 and #51. Have you tried the solutions presented in those issues?

**Comment by ynusinovich** [comment]
Thank you for your help. My apologies, I missed those.

I also had to change `dataset._characters` to `dataset.labels` to make the code work, in case that's useful to anyone.

With just 16 images in 4 classes, and no training yet, it got 55% accuracy.
