### ISSUE TITLE
SupportSetFolder not included in latest release

### ISSUE THREAD

**Issue by rlleshi** [sicara/easy-few-shot-learning#60]
First of all, great repo, very useful!

I was wondering when will you release the next version that includes the [SupportSetFolder](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/support_set_folder.py) class to the latest PyPi distribution.

**Comment by ebennequin** [comment]
Hi! You're right, it's been in the lobby for too long. I'll release v1.1.0 next week so `SupportSetFolder` can be used with PyPi.

Thanks for the reminder!
