### ISSUE TITLE
Adding more backbones 

### ISSUE THREAD

**Issue by anish9** [sicara/easy-few-shot-learning#62]
Hi @ebennequin, Thanks for this elegant  code base, some questions(can be a feature request)
 1) Can we add new backbones like (ViT, densenet, Convnext etc...)?
 2) Building functionalities for model deployments?

**Comment by ebennequin** [comment]
Hi, thanks for the kind words.

1. You can pass any backbone when building your `FewShotClassifier`, so you can use backbones like ViT, DenseNet, ConvNeXt from well-maintained libraries like [timm](https://github.com/rwightman/pytorch-image-models). In this repo I added custom backbones that are hardly SOTA but are often used when benchmarking FSL.
2. This repo is mainly targeted to research and education, not for production, so features for model deployment are not on the roadmap. However, I'd love to discuss it if you think we can add some useful stuff!

**Comment by rlleshi** [comment]
@anish9 I think model deployment is pretty straightforward. `easyfsl` is a very light library, so even if you don't want to convert models (e.g. to TorchServe or onxx) you can simply install the library & use [SupportSetFolder](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/support_set_folder.py) for example.

Maybe adding a script to convert models would be a good idea though.
