### ISSUE TITLE
N_QUERY

### ISSUE THREAD

**Issue by earthlovebpt** [sicara/easy-few-shot-learning#63]
1. The number of query set of each class has to be equal? Can i use random number of images of each class.
2. Training epoch by epoch still can be used in few-shot learning?
![306034091_661392165355129_2531247296356843848_n](https://user-images.githubusercontent.com/78471470/195814702-cac82088-c060-4871-8aa1-77c9265eafcb.png)

**Comment by ebennequin** [comment]
Hello.

1. You can use unbalanced query sets if you like, it doesn't matter to the `forward` method of `FewShotClassifier`.
2. Yes, why not?

**Comment by earthlovebpt** [comment]
![image](https://user-images.githubusercontent.com/78471470/196087900-7ac1ba60-eb88-4289-ae73-75ae62b532be.png)
When i trained model, i got werid learning curve. So i wonder that i did something wrong?
<img width="710" alt="image" src="https://user-images.githubusercontent.com/78471470/196088335-769e6e53-5ea4-4e6b-8436-215f4736217d.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/78471470/196088385-63ba5489-9b78-48c2-aba8-9deae8324b76.png">

**Comment by ebennequin** [comment]
I'm sorry I can't help you with this amount of information. If you can share a working Google Colab that I can run to reproduce your issue, I might be able to help you.
