### ISSUE TITLE
how to evaluate model's accuary about few classes? 

### ISSUE THREAD

**Issue by cy2333ytu** [sicara/easy-few-shot-learning#66]
**Problem**
Hello, In Classical_Training.py, I have five classes in teset set,  by using [evaluate ](https://github.com/sicara/easy-few-shot-learning/blob/6e27907d2a8194ac0ab100c3734773c93f1aadf5/easyfsl/methods/utils.py) function, can get five classes' average accuary,  but I want to get every class's accuary, how can i achieve this?, thanks

**Comment by cy2333ytu** [comment]
I use few test.json to achieve this

**Comment by ebennequin** [comment]
Hi, notice that in `evaluate_on_one_task()` we only report the number of correct predictions and the total number of samples. But you can easily access the complete predictions by removing the aggregation:

```python
model.process_support_set(support_images, support_labels)
return torch.max(
        model(query_images).detach().data,
        1,
)[1]
```
