### ISSUE TITLE
For custom datasets, how to divide the class?

### ISSUE THREAD

**Issue by ssx12042** [sicara/easy-few-shot-learning#67]
Hi. Thank you for your great work and sharing it with everyone.

I have a question.
For custom datasets, how to divide the class? (train, val, test) Randomly select some classes as the training set, or?
Do you have any tricks?

**Comment by ebennequin** [comment]
Hi, thank you for your kind words.

I would say it depends on what your criteria for a good split are.

**Comment by diego91964** [comment]
Do you know the lib from sklearn.model_selection KFold? 

Another option is to use  a direct folder separtion like this example:

``


def n_fold_dataset (input_path : str , fold_config, output_path = None, n_folds = 1 , soft = True):

    if os.path.isdir(input_path):
        number_of_classes = len([name for name in os.listdir(input_path) if os.path.isdir(input_path)])
        # name for name in os.listdir(os.path.join(input_path,subfolder))
        number_of_images_by_class = np.array([ len(os.listdir(os.path.join(input_path,subfolder))) for ix, subfolder in enumerate([ subfolder for id, subfolder in enumerate(os.listdir(input_path))])])
        min = np.min(number_of_images_by_class)
        number_of_images_to_select = [ (x[0], floor(x[1] * min)) for x in fold_config]

        for fold_numer in range (n_folds):

            if not soft:
               output_path_fold =  os.path.join(output_path,"fold_{}".format(fold_numer))
               if not os.path.isdir(output_path_fold):
                os.makedirs(output_path_fold)

            all_image_class = np.array([ (subfolder,os.listdir(os.path.join(input_path, subfolder))) for ix, subfolder in enumerate( [subfolder for id, subfolder in enumerate(os.listdir(input_path))])])

            for i, number_of_images_tuple in enumerate(number_of_images_to_select):
                name_of_set = number_of_images_tuple[0]
                number_of_images = number_of_images_tuple[1]
                for ix , image_tuple in enumerate(all_image_class):
                    clasz = image_tuple[0]
                    image_class = image_tuple[1]
                    selected_images , resultant_list = get_random_elements(image_class, number_of_images)
                    all_image_class[ix] = (clasz, resultant_list)

                    if not soft:
                        for jx, selected_image in enumerate (selected_images):
                            if not os.path.isdir (os.path.join(output_path_fold,name_of_set,clasz)):
                                os.makedirs(os.path.join(output_path_fold,name_of_set,clasz))
                            src_d =  os.path.join(input_path,clasz,selected_image)
                            dst_d =  os.path.join(output_path_fold,name_of_set,clasz,selected_image)
                            shutil.copy(src_d,dst_d)
                    else:
                        print("{} Selected Images:({}) {}".format(len(selected_images),clasz, selected_images))

``

The 'fold_config' param is the configuration of the percent of images in each group.

fold_config= [ ('train', 0.45) ,('test', 0.27),('eval', 0.27)],

The input_path is the folder that contains classes folders

If soft param is true, the method only simulate the execution.

This is just an example, hope it helps.

**Comment by maria-zafar** [comment]
Hello, I have my own dataset how can I use this code to align with my dataset instead of omniglot-py dataset

**Comment by ssx12042** [comment]
> Hi, thank you for your kind words.
> 
> I would say it depends on what your criteria for a good split are.

Thank you for your reply.

**Comment by ssx12042** [comment]
> Do you know the lib from sklearn.model_selection KFold?
> 
> Another option is to use a direct folder separtion like this example:
> 
> ``
> 
> def n_fold_dataset (input_path : str , fold_config, output_path = None, n_folds = 1 , soft = True):
> 
> ```
> if os.path.isdir(input_path):
>     number_of_classes = len([name for name in os.listdir(input_path) if os.path.isdir(input_path)])
>     # name for name in os.listdir(os.path.join(input_path,subfolder))
>     number_of_images_by_class = np.array([ len(os.listdir(os.path.join(input_path,subfolder))) for ix, subfolder in enumerate([ subfolder for id, subfolder in enumerate(os.listdir(input_path))])])
>     min = np.min(number_of_images_by_class)
>     number_of_images_to_select = [ (x[0], floor(x[1] * min)) for x in fold_config]
> 
>     for fold_numer in range (n_folds):
> 
>         if not soft:
>            output_path_fold =  os.path.join(output_path,"fold_{}".format(fold_numer))
>            if not os.path.isdir(output_path_fold):
>             os.makedirs(output_path_fold)
> 
>         all_image_class = np.array([ (subfolder,os.listdir(os.path.join(input_path, subfolder))) for ix, subfolder in enumerate( [subfolder for id, subfolder in enumerate(os.listdir(input_path))])])
> 
>         for i, number_of_images_tuple in enumerate(number_of_images_to_select):
>             name_of_set = number_of_images_tuple[0]
>             number_of_images = number_of_images_tuple[1]
>             for ix , image_tuple in enumerate(all_image_class):
>                 clasz = image_tuple[0]
>                 image_class = image_tuple[1]
>                 selected_images , resultant_list = get_random_elements(image_class, number_of_images)
>                 all_image_class[ix] = (clasz, resultant_list)
> 
>                 if not soft:
>                     for jx, selected_image in enumerate (selected_images):
>                         if not os.path.isdir (os.path.join(output_path_fold,name_of_set,clasz)):
>                             os.makedirs(os.path.join(output_path_fold,name_of_set,clasz))
>                         src_d =  os.path.join(input_path,clasz,selected_image)
>                         dst_d =  os.path.join(output_path_fold,name_of_set,clasz,selected_image)
>                         shutil.copy(src_d,dst_d)
>                 else:
>                     print("{} Selected Images:({}) {}".format(len(selected_images),clasz, selected_images))
> ```
> 
> ``
> 
> The 'fold_config' param is the configuration of the percent of images in each group.
> 
> fold_config= [ ('train', 0.45) ,('test', 0.27),('eval', 0.27)],
> 
> The input_path is the folder that contains classes folders
> 
> If soft param is true, the method only simulate the execution.
> 
> This is just an example, hope it helps.

Thanks for your help. I think I should try to use this code.

**Comment by shraddha291996** [comment]
> Hello, I have my own dataset how can I use this code to align with my dataset instead of omniglot-py dataset

Hi I have a same question did you get any idea?

**Comment by diego91964** [comment]
> Hello, I have my own dataset how can I use this code to align with my dataset instead of omniglot-py dataset

This code is intended for custom datasets, the images need to be organized into folders:

dataset:
-- class1
-- class2
...
-- classN

**Comment by maria-zafar** [comment]
I did that but this is not helping

**Comment by ebennequin** [comment]
Hi, can you show us what you did and what was the output?

**Comment by maria-zafar** [comment]
Yes, I have used your class EasySet and based on its structure prepared the data using json file now the problem is with inference that I just want to pass an image and it should predict the class of an image.  The method that you have shared is different and doesn't support the model format

**Comment by ebennequin** [comment]
It's hard to help you solve your problem with that level of information. Could you please share your code, the result that you are expecting and the result that you are getting?

**Comment by maria-zafar** [comment]
Can I have your email so that I could share my colab notebook?

**Comment by ebennequin** [comment]
If it's not too much trouble I'd rather you share here so the solution we find can benefit others with the same problem.

**Comment by maria-zafar** [comment]
yes I will share it later for the use of other but for now its a bit confidential work so I'll change later and post the link here as well

**Comment by shraddha291996** [comment]
> yes I will share it later for the use of other but for now its a bit confidential work so I'll change later and post the link here as well

hello @maria-zafar , did you find any solution for this? If yes can you please share an example? as I have been looking for same question.
Thanks in advance
