### ISSUE TITLE
How to get a prediction for custom dataset ?

### ISSUE THREAD

**Issue by shraddha291996** [sicara/easy-few-shot-learning#70]
Hello, Thank you very much for your amazing work, its very helpful.

I have one question on getting prediction on custom dataset, so basically I am using **Easyset** for my custom dataset and **classical training notebook** and I want to see prediction/classification also , for example from which class my test image belongs to. 
I hope my quetsion is clear to you.
Thanks  in advance

**Comment by diego91964** [comment]
#17 

I hope that this Issue could help you
