### ISSUE TITLE
classical training method evaluation concept

### ISSUE THREAD

**Issue by joshuasir** [sicara/easy-few-shot-learning#71]
Hello, i'm new to few shot learning and want to make sure about classical training. When the backbone, after training, is evaluated with a picked method on new set of data, does the method get adjusted or learn from the new data?

**Comment by ebennequin** [comment]
Hi,

If by "learning" you mean that the weights of the backbone are updated, then no, most methods in this library don't "learn" on new data. Instead they use the pre-trained backbone to cast images into a feature space, and compare images in this feature space.

**Comment by joshuasir** [comment]
thanks for the reply, sorry for asking basic questions so the methods works in unsupervised sense? as in no prior "learning" needed

**Comment by ebennequin** [comment]
It's not unsupervised, you still need to have your few examples labelled.

**Comment by joshuasir** [comment]
sorry i mean for the comparing images in the feature space part

**Comment by joshuasir** [comment]
i think i got it thank you for your time i really appreciate it
