### ISSUE TITLE
Can I use different backbone for classical or episodic learning ?

### ISSUE THREAD

**Issue by shraddha291996** [sicara/easy-few-shot-learning#72]
Hi, 

I am using your classical and episodic Training notebooks, they are very helpful for my project , although I want to try different backbones like EfficientNet. I am new in this so do you have any idea if I can use different backbone than ResNet if yes what changes I will have to consider in the code? 

Thanks in adavance

**Comment by ebennequin** [comment]
Hi! As you can see in `FewShotClassifier`'s [documenation](https://github.com/sicara/easy-few-shot-learning/blob/5baddc36620b907723ea69bf850560b34b4cf1dd/easyfsl/methods/few_shot_classifier.py#L17), the backbone can be any module that outputs a tensor of the appropriate shape. The appropriate shape depends on the method, but for most methods it's a one-dimensional tensor.

It's common practice to use any pre-trained module, and just remove the last linear layer (which shape often depends on the training classes). EfficientNet should be fine.
