### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate :) (GPU 0; :) GiB total capacity; :) GiB already allocated; :) MiB free; :) GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by shraddha291996** [sicara/easy-few-shot-learning#73]
Hello,

I am Running Episodic training with Matching Network and backbone ViT. I get the error CUDA out of memory. 
My FSL setting is : 
Nway- 9
Nshot- 10
Nquery- 10 
batch size- 2
I am also resizing the my dataset rgb images with 224 by 224 .
Could anyone please help me with this issue?
One thing when I am running Classical training with Prototypical network and Efficient backbone with same setting its running fine.

Thanks in advance

**Comment by ebennequin** [comment]
Your setting corresponds to a batch of size `9 * (10+10) = 180`. It's likely that training a ViT with that batch size is too costly for your GPU.

I suggest you reduce the number of ways, shots or queries.

**Comment by shraddha291996** [comment]
> Your setting corresponds to a batch of size `9 * (10+10) = 180`. It's likely that training a ViT with that batch size is too costly for your GPU.
> 
> I suggest you reduce the number of ways, shots or queries.

Thanks for your reply, In my case I have 94 classes but right now I use just 9 for testing, so I cannot reduce the number of ways but I tried to use lighter backbone (inception_resnet_v2) and reduced number of batches to 1 and number of epoch to 5 but then results are very bad :(.
