### ISSUE TITLE
Batch Size in Episodic and My-first-few-shot-classfier?

### ISSUE THREAD

**Issue by shraddha291996** [sicara/easy-few-shot-learning#78]
Hi,

I have a question about **size of batch** and **the number of images in each batch** in episodic and my-first-few-shot-classifier notebooks . As you mentioned in your [https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb](url) number of images in each batch calculated with (nway*(nshot+nquery)) then what is the size of batch or its same like number of images in each batch?
Thanks in Advance

**Comment by ebennequin** [comment]
A batch (or task in few-shot) is indeed of size `n_way * (n_shot + n_query)`, as explained in the notebook.
