### ISSUE TITLE
What is the difference between support images used in training and support images used in testing ?

### ISSUE THREAD

**Issue by shraddha291996** [sicara/easy-few-shot-learning#79]
Hello, 

I have a very basic question on support images used in testing phase, I know that they are used for evaluation of the model but what is their exact role ? As support images in training phase are used for model training and prototypes are created in the training phase. What happens in testing with support images?
Thanks in advance

**Comment by ebennequin** [comment]
From [this article on FSL](https://www.sicara.fr/blog-technique/2019-07-30-image-classification-few-shot-meta-learning):

> Given:
> 
> 1. a support set composed of N labels and, for each label, K labeled images;
> 2. a query set composed of Q query images;
> 
> the [few-shot] task is to classify the query images among the N classes given the N×Kimages in the support set. When K is small (typically K<10), we talk about few-shot image classification (or one-shot in the case where K=1).

Support images is the labeled data that you have to define your few-shot classes.
