### ISSUE TITLE
Calculate the confusion matrix for binary classification

### ISSUE THREAD

**Issue by haricash** [sicara/easy-few-shot-learning#80]
I have a binary classification task for which I am using EasyFSL. I am new to PyTorch (and programming in general) and I am having a tough time implementing a custom evaluate function that will calculate the confusion matrix of the binary classification task.

A guide to how I could go about this would be helpful - I can try and implement the same by myself!

**Comment by ebennequin** [comment]
Hi! I think this is similar to #50 

There are built-in [torch](https://pytorch.org/ignite/generated/ignite.metrics.confusion_matrix.ConfusionMatrix.html) or [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html) methods for confusion matrix that you could use.
