### ISSUE TITLE
Unable to run EasyFSL on my own Dataset

### ISSUE THREAD

**Issue by Anin1** [sicara/easy-few-shot-learning#85]

**Comment by Anin1** [comment]
Please help me to run EasyFSL code on my own database using database path address.

**Comment by ebennequin** [comment]
Hello.

As it is, I don't know anything about your issue, so I have no clue on how to help you. I encourage you to read [this tutorial on how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report). Namely, I need to know how to reproduce your error (OS, version, where is your dataset, what code generated an error, what was the stack trace...).

**Comment by Anin1** [comment]
How to add my own dataset path on EasyFSL code? 
I run EasyFSL on Colab and my dataset is on my google drive. I add my dataset path on EasyFSL code. But errors occur in the Training phase [line: train_set.get_labels = lambda: [instance[1] for instance in train_set._flat_character_images]
Please suggest how to run EasyFSL on my own dataset using the dataset path address.
