### ISSUE TITLE
I want to run EasyFSL code on my own dataset 

### ISSUE THREAD

**Issue by Anin1** [sicara/easy-few-shot-learning#87]
How to add my own dataset path on EasyFSL code?
I run EasyFSL on Colab and my dataset is on my google drive. I add my dataset path on EasyFSL code. But errors occur in the Training phase. **Please suggest how to run EasyFSL on my own dataset using the dataset path address.**

**Comment by ebennequin** [comment]
I still can't help you if you won't share your code and the stack trace.
