### ISSUE TITLE
TaskSampler.episodic_collate_fn(): IndexError: Target 7 is out of bounds.

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [sicara/easy-few-shot-learning#89]
**Problem**

I'm trying to use relational networks for a binary classification problem, I used the code from the episodic training tutorial but I encountered some problems while doing that and I think that the source of those problems is the TaskSampler class

The first error message that I got was "IndexError: Target 2 is out of bounds.", that error message was always changing: sometimes it was "IndexError: Target 7 is out of bounds." and other times, that error didn't show up! I printed the query labels and by looking at them, I noticed that it's always a list of zeros and a number that shows on the error message so I wrote a for loop to change the values of the query labels list to be always zeros and 1 and that solved the first problem.
You can find my code to reproduce the first error right [here](https://www.kaggle.com/amlhassan/rn-with-binary-classification)

 the second problem that happened  after that was the fact that the output of the model "classification_scores" was most of the times = nan, I was sure that my dataset didn't contain any nans, so I checked if there were an overflow or something like that and there was no overflow, finally I traced back the error until I found that those nans come from the output of the compute_prototypes function, **The output for that function contained no nans and I checked that multiple times**
I managed to fix that by changing the list that the for loop loops through to be the list of the support labels directly instead of its length, you can see the changes below and you can see the full code [here](https://www.kaggle.com/amlhassan/fixing-the-null-problem)

def compute_prototypes(support_features: Tensor, support_labels: Tensor) -> Tensor:​

    #n_way = len(torch.unique(support_labels))

    n_way = torch.unique(support_labels).tolist()

    return torch.cat(
        [
            support_features[torch.nonzero(support_labels == label)].mean(0)
            for label in n_way#range(n_way)
        ]
    )

**Considered solutions**

I find that the main problem comes from the fact that the method "episodic_collate_fn" from the TaskSampler class doesn't return the original labels, so can we change that without messing anything up?

**How can we help**
First of all: can you please tell me if any of the fixes that I have done above is wrong? and if anything was wrong how can I fix it the right way?

second: I want to know if the index in the relation score represents the class or not. and if it's not how could I get the right class? to be clearer, I'm trying to write a function to measure some metrics, so I need the prediction and that's how I extract them: 
```
pred=few_shot_classifier(torch.FloatTensor(X_test[0:batch_size].values).reshape(batch_size,1,1,30).expand(-1,3,-1,-1).to(device))

roc_auc_score(torch.FloatTensor(y_test.values)[0:batch_size].data.cpu().numpy(), pred.data.argmax(1).cpu().numpy())

```

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Thanks @ebennequin for your response.
From what you're saying, I guess that the way that I tried to fix my errors with are wrong.
Can you please take a look at that [Code ](https://www.kaggle.com/amlhassan/rn-with-binary-classification)  and tell me how to fix that error ?

**Comment by ebennequin** [comment]
Sadly I can't, the code seems inaccessible.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/45969336/224689054-06292400-ef1b-4272-ba3c-dd7ff555a441.png">

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
I'm so sorry for that mistake @ebennequin  here is another  [Link](https://github.com/Aml-Hassan-Abd-El-hamid/Machine-learning-college-course/blob/main/rn-with-binary-classification-first-error.ipynb)

**Comment by ebennequin** [comment]
THank you this is helpful. Can you print out the list of true class IDs ? This would help a lot. It is the variable that is currently ignored in your code:

```python
for episode_index, (
            support_images,
            support_labels,
            query_images,
            query_labels,
            _,  # This one
        ) in tqdm_train:
``

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Thank you for your help @ebennequin 
I printed it and that was the output:
`query_labels  tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
true_class_IDs  [tensor(0), tensor(0), tensor(0), tensor(1), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(0), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(1), tensor(0), tensor(0), tensor(0)]`

Also, I tried to set up the notebook again, and I think this time it will be working, you can find it [here](https://www.kaggle.com/code/amlhassan/rn-with-binary-classification-first-error)

**Comment by ebennequin** [comment]
Ahh I got it!

Your dataset's `__get_item__()` method returns a `tuple(Tensor, Tensor)` object, while `TaskSampler.episodic_collate_fn()` expects a `list(tuple(Tensor, int))` (as explicited in [the method's typing](https://github.com/sicara/easy-few-shot-learning/blob/cb162e0546a292fcd1f16758cb7fdb342de83c10/easyfsl/samplers/task_sampler.py#L67)).

An object with the value `tensor(3)` is very different from an integer with the value `3`. A key difference is of interest to us here: the following lines of code will have a very different behavior:

```python
input_data = [
            (..., 0),
            (..., 0),
            (..., 3),
            (..., 3),
        ]

true_class_ids = list({x[1] for x in input_data})
```
Gives `[0,3]`. However:

```python
input_data = [
            (..., torch.tensor(0)),
            (..., torch.tensor(0)),
            (..., torch.tensor(3)),
            (..., torch.tensor(3)),
        ]

true_class_ids = list({x[1] for x in input_data})
```
Here `true_class_ids = [torch.tensor(0), torch.tensor(0), torch.tensor(3), torch.tensor(3)]`

In the code for `episodic_collate_fn()`, we will define the task-level labels as the index of each class ID in `true_class_ids`. If you ensure that `true_class_ids` is of length `n_way` (case 1), it works fine, but in case 2 it will create labels greater than `n_way` (like in your case).

**How to fix your problem**

Ensure that your dataset returns labels as an integer, not as a tensor of an integer.

**How to improve EasyFSL**

Two options: either raise an explicit `TypeError` when the label is not an integer, or allow singleton tensors and make it work (still raising a `ValueError` if tensor is not a singleton). In any case, we probably need to focus on sanity checks for `TaskSampler`. I'm labelling this as enhancement.

Thank you for raising this issue, it will make EasyFSL better!

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Thank you @ebennequin so much for your help! I really appreciate it.
I actually didn't know that I have to re-write the __getitem__() method, It's a built-in function and it wasn't mentioned in the tutorials, So I think allowing singleton tensors and making it work is a better solution for such situation as it will be much easier for the user, If you don't mind, I think that I can make a PR with that.

**Comment by ebennequin** [comment]
That would be very helpful, thank you!
