### ISSUE TITLE
pre-trained weights for the ResNet12？

### ISSUE THREAD

**Issue by ssx12042** [sicara/easy-few-shot-learning#91]
Hi, thank you for your excellent work. I would like to ask if there are pre-trained weights for the resnet12 model?

**Comment by ebennequin** [comment]
Hi, thank you for your kind words! I have some ResNet12 pre-trained weights referenced [here](https://github.com/ebennequin/few-shot-open-set#download-models).

**Comment by ssx12042** [comment]
OK. THANKS.
