### ISSUE TITLE
Difference between training style

### ISSUE THREAD

**Issue by KyleChenpopo** [sicara/easy-few-shot-learning#92]
Hi, thank you for giving us this wonderful work. When I tried those examples, I still confused about those three training style, the following files are:
1. First steps into few-shot image classification
2. Example of episodic training
3. Example of classical training

I'm wondering what is difference of training style between file 1 and file 3, the train set seems to used different way. One is batch_size, one is train_sampler, could you explain more detail about the difference between them? Is the classical training still belongs to few-shot learning style? Thanks for the answer!

And in the last part of classical training, you mentioned the test data that evaluate on the same shape of tasks as in validation, but I saw the json files that are already divied the train/val/test, so isn't that meaning the test data not including inside the training? Because I'm still learning so sorry for many questions!

**Comment by ebennequin** [comment]
The training process described in https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/my_first_few_shot_classifier.ipynb is episodic training, so roughly the same as https://github.com/sicara/easy-few-shot-learning/blob/master/notebooks/episodic_training.ipynb, although they have been made at different times so there must be some differences in style.

I am not sure I understand your confusion between `batch_size` and `train_sampler`, which are very different objects in nature. Could you be more specific?

> And in the last part of classical training, you mentioned the test data that evaluate on the same shape of tasks as in validation, but I saw the json files that are already divied the train/val/test, so isn't that meaning the test data not including inside the training? Because I'm still learning so sorry for many questions!

What I wrote in the notebook is this: 

> First step: we fetch the test data. Note that we'll evaluate on the same shape of tasks as in validation. This is malicious practice, because it means that we used a priori information about the evaluation tasks during training. This is still less malicious than episodic training, though.

It means that even though the data is properly split between train/val/test so test data doesn't appear during training, by using the same shape of task (e.g. same `n_way`) I am assuming that at training time I already know what my test tasks are going to look like, which is a very strong assumption.
